import { readFileSync, writeFileSync } from 'fs';
import sharp from 'sharp';

const SK = '/Users/courtneebonnick/Library/Application Support/Claude/local-agent-mode-sessions/skills-plugin/28b47369-9e8a-4d10-9998-5d34ca05aee3/1656b4c2-e79d-4206-bfa5-50c3e0744680/skills/handy-services-pdf';

async function main() {
  const reg = readFileSync('/tmp/poppins/Poppins-Regular.ttf').toString('base64');
  const bold = readFileSync('/tmp/poppins/Poppins-Bold.ttf').toString('base64');
  const ital = readFileSync('/tmp/poppins/Poppins-Italic.ttf').toString('base64');
  const logoPng = await sharp(`${SK}/assets/logo.png`).resize(160, 160, { fit: 'inside' }).png({ quality: 90 }).toBuffer();
  const logo = `data:image/png;base64,${logoPng.toString('base64')}`;

  const out = `// AUTO-GENERATED by scripts/_gen-pdf-assets.ts — do not edit by hand.
// Handy Services brand assets for the quote PDF: the circular hand logo (PNG data
// URL) and Poppins TTFs (base64) matching the handy-services-pdf skill. Loaded via
// dynamic import() so this ~640KB payload is code-split out of the main bundle and
// only fetched when a customer downloads their quote.
/* eslint-disable */
export const LOGO_DATA_URL = ${JSON.stringify(logo)};
export const POPPINS_REGULAR = ${JSON.stringify(reg)};
export const POPPINS_BOLD = ${JSON.stringify(bold)};
export const POPPINS_ITALIC = ${JSON.stringify(ital)};
export const brandAssets = {
  logoDataUrl: LOGO_DATA_URL,
  poppins: { regular: POPPINS_REGULAR, bold: POPPINS_BOLD, italic: POPPINS_ITALIC },
};
`;
  writeFileSync('client/src/lib/quote-pdf-brand-assets.ts', out);
  console.log(`wrote quote-pdf-brand-assets.ts — logo ${(logoPng.length/1024).toFixed(0)}KB, fonts ${((reg.length+bold.length+ital.length)/1024).toFixed(0)}KB b64`);
}
main().catch(e=>{console.error(e);process.exit(1);});
