CREATE TABLE "personalized_quotes" (
	"id" varchar PRIMARY KEY NOT NULL,
	"short_slug" varchar(8) NOT NULL,
	"customer_name" varchar NOT NULL,
	"phone" varchar NOT NULL,
	"email" varchar,
	"postcode" varchar,
	"job_description" text NOT NULL,
	"completion_date" varchar,
	"tasks" text[],
	"categories" varchar(50)[],
	"substrates" varchar(50)[],
	"materials_by" varchar(20),
	"urgency" varchar(20),
	"persona" varchar(20),
	"risk" integer,
	"jobs" jsonb,
	"context_signals" jsonb,
	"urgency_reason" varchar(20),
	"ownership_context" varchar(20),
	"desired_timeframe" varchar(20),
	"base_job_price_pence" integer,
	"value_multiplier_100" integer,
	"recommended_tier" varchar(20),
	"additional_notes" text,
	"tier_deliverables" jsonb,
	"pvs_score" integer,
	"value_multiplier" integer,
	"dominant_category" varchar,
	"anchor_price" integer,
	"quote_mode" varchar(10) DEFAULT 'hhh' NOT NULL,
	"essential_price" integer,
	"enhanced_price" integer,
	"elite_price" integer,
	"base_price" integer,
	"optional_extras" jsonb,
	"materials_cost_with_markup_pence" integer DEFAULT 0,
	"value_opportunities" jsonb,
	"emotional_angle" varchar,
	"personalized_features" jsonb,
	"core_deliverables" jsonb,
	"potential_upgrades" jsonb,
	"potential_extras" jsonb,
	"desirables" jsonb,
	"viewed_at" timestamp,
	"selected_package" varchar,
	"selected_extras" jsonb,
	"selected_at" timestamp,
	"booked_at" timestamp,
	"lead_id" varchar,
	"expires_at" timestamp,
	"regenerated_from_id" varchar,
	"regeneration_count" integer DEFAULT 0,
	"extension_count" integer DEFAULT 0,
	"payment_type" varchar(20),
	"stripe_customer_id" varchar,
	"stripe_subscription_schedule_id" varchar,
	"stripe_payment_method_id" varchar,
	"stripe_payment_intent_id" varchar,
	"installment_status" varchar(20),
	"installment_amount_pence" integer,
	"total_installments" integer DEFAULT 3,
	"completed_installments" integer DEFAULT 0,
	"next_installment_date" timestamp,
	"deposit_paid_at" timestamp,
	"deposit_amount_pence" integer,
	"selected_tier_price_pence" integer,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "personalized_quotes_short_slug_unique" UNIQUE("short_slug")
);
