/**
 * Contextual Pricing Engine — Shared Types
 *
 * All TypeScript interfaces shared between server and client for the
 * contextual pricing engine. This engine replaces the multiplier-based
 * EVE approach with a layered system:
 *
 *   Layer 1: Reference rates (market-grounded hourly rates per job category)
 *   Layer 3: LLM contextual pricing (adjusts based on full context)
 *   Layer 4: Guardrails (floor/ceiling/margin checks)
 *
 * Segment type is intentionally kept as `string` here to avoid
 * duplicating the LeadSegment type from schema.ts — callers should
 * use LeadSegment from schema.ts when constructing PricingContext.
 */

// ---------------------------------------------------------------------------
// Job Categories
// ---------------------------------------------------------------------------

/** All job categories for a Nottingham handyman business */
export const JobCategoryValues = [
  'general_fixing',     // Shelf hanging, curtain rails, picture hanging
  'flat_pack',          // IKEA/furniture assembly
  'tv_mounting',        // TV wall mounting
  'carpentry',          // Door fitting, skirting, built-in shelves
  'plumbing_minor',     // Tap replacement, toilet repair, radiator bleed
  'electrical_minor',   // Socket fitting, light fixture, extractor fan
  'painting',           // Interior painting, touch-ups
  'tiling',             // Tiling, grouting, silicone work
  'plastering',         // Patch plastering, skim coat
  'lock_change',        // Lock replacement, door security
  'guttering',          // Gutter clearing, downpipe repair
  'pressure_washing',   // Driveway, patio cleaning
  'fencing',            // Fence panel replacement, post repair
  'garden_maintenance', // Garden tidying, shed assembly
  'bathroom_fitting',   // Full bathroom install (complex)
  'kitchen_fitting',    // Kitchen install (complex)
  'door_fitting',       // Door hanging, internal/external door fitting
  'flooring',           // Laminate, vinyl, engineered wood flooring
  'curtain_blinds',     // Curtain rails, blinds fitting, roller blinds
  'silicone_sealant',   // Re-sealing baths, showers, sinks
  'shelving',           // Shelf installation, floating shelves, brackets
  'furniture_repair',   // Furniture fixes, drawer runners, hinge replacement
  'waste_removal',      // Rubbish clearance, old furniture disposal
  'other',              // Catch-all
] as const;

export type JobCategory = typeof JobCategoryValues[number];

/**
 * @deprecated Use JobCategoryValues instead. Kept for backward compatibility.
 */
export const JOB_CATEGORIES = JobCategoryValues;

// ---------------------------------------------------------------------------
// Layout & Booking Types
// ---------------------------------------------------------------------------

/** Recommended quote page layout complexity */
export type LayoutTier = 'quick' | 'standard' | 'complex';

/**
 * Deterministic layout tier based on line item count.
 *   1 line   → 'quick'
 *   2-3 lines → 'standard'
 *   4+ lines  → 'complex'
 */
export function getLayoutTier(lineCount: number): LayoutTier {
  if (lineCount <= 1) return 'quick';
  if (lineCount <= 3) return 'standard';
  return 'complex';
}

/** Available booking mode options shown on the quote page */
export type BookingMode = 'standard_date' | 'flexible_discount' | 'urgent_premium' | 'deposit_split';

// ---------------------------------------------------------------------------
// Quote Messaging (LLM-generated customer-facing content)
// ---------------------------------------------------------------------------

/** Customer-facing messaging generated by the LLM alongside pricing */
export interface QuoteMessaging {
  /** Customer-facing headline, e.g. "Your Kitchen Sorted" */
  contextualHeadline: string;
  /** 1-2 sentence summary for the customer */
  contextualMessage: string;
  /** 3-7 word polished job summary for the hero, e.g. "Dripping tap sorted for good" */
  jobTopLine?: string;
  /** AI-generated scope-of-work summary (2-4 sentences, 40-80 words) */
  proposalSummary: string;
  /** 3-5 approved claim bullets for the quote page */
  valueBullets: string[];
  /** Exactly 2 value lines for WhatsApp message */
  whatsappValueLines: string[];
  /** Closing line for WhatsApp message */
  whatsappClosing: string;
  /** Recommended layout: quick/standard/complex */
  layoutTier: LayoutTier;
  /** Which booking options to show on the quote page (deterministic, not LLM) */
  bookingModes: BookingMode[];
  /** True if AI parser fallback was triggered */
  requiresHumanReview: boolean;
  /** Why human review is needed (only set when requiresHumanReview is true) */
  reviewReason?: string;
  /**
   * Dead zone framing note shown near the price when the quote lands in the
   * £100-£200 band (0% conversion in analytics). E.g. "That's around £5 a
   * day for 30 days of not having to think about this."
   */
  deadZoneFraming?: string;
}

// ---------------------------------------------------------------------------
// Category Rate (used by reference price lookup)
// ---------------------------------------------------------------------------

/**
 * Market rate data for a single job category (all values in pence).
 */
export interface CategoryRate {
  /** Typical hourly rate in pence */
  hourly: number;
  /** Minimum job charge in pence (covers callout / first-hour cost) */
  min: number;
  /** Low end of the market range in pence */
  low: number;
  /** High end of the market range in pence */
  high: number;
  /** Data source attribution */
  source: string;
}

// ---------------------------------------------------------------------------
// Pricing Context — every signal the pricing engine can use
// ---------------------------------------------------------------------------

export interface PricingContext {
  // -- Job signals (from transcript / SKU detection) --

  /** Free-text description of the work requested */
  jobDescription: string;
  /** Detected job category */
  jobCategory: JobCategory;
  /** Estimated time to complete the job in minutes */
  timeEstimateMinutes: number;
  /** Number of jobs in this batch (1 = single job, 2+ = batch) */
  jobCountInBatch: number;

  // -- Customer signals (from segment detection + CRM) --

  /** Customer segment (e.g. BUSY_PRO, LANDLORD). Use LeadSegment from schema.ts. */
  segment: string;
  /** Whether the customer has booked with us before */
  isReturningCustomer: boolean;
  /** Number of previous completed jobs for this customer */
  previousJobCount: number;
  /** Average price paid on previous jobs, in pence (null if new customer) */
  previousAvgPricePence: number | null;

  // -- Situational signals (from transcript + booking) --

  /** How urgently the customer needs the work done */
  urgency: 'standard' | 'priority' | 'emergency';
  /** Access difficulty at the job site */
  accessDifficulty: 'standard' | 'loft' | 'high_ceiling' | 'crawlspace' | 'no_parking';
  /** Who is supplying materials */
  materialsSupply: 'customer_supplied' | 'we_supply' | 'labor_only';
  /** When the work will be carried out */
  timeOfService: 'standard' | 'after_hours' | 'weekend';
  /** Travel distance from base in miles */
  travelDistanceMiles: number;

  // -- Business signals (from operations) --

  /** Current capacity utilisation, 0-100 (higher = busier) */
  currentCapacityPercent: number;
}

// ---------------------------------------------------------------------------
// Layer 1: Reference Rate
// ---------------------------------------------------------------------------

/** Output from the reference rate lookup */
export interface ReferenceRateResult {
  /** Job category used for the lookup */
  category: JobCategory;
  /** Market hourly rate in pence */
  hourlyRatePence: number;
  /** Minimum charge in pence (floor for very short jobs) */
  minimumChargePence: number;
  /** Calculated reference price: hourlyRate * (time / 60), floored at minimum */
  calculatedReferencePence: number;
  /** Local market rate range for this category */
  marketRange: { lowPence: number; highPence: number };
  /** Where the rate data came from (e.g. "checkatrade_2025", "internal") */
  source: string;
}

// ---------------------------------------------------------------------------
// Layer 3: LLM Contextual Pricing
// ---------------------------------------------------------------------------

/** A single adjustment the LLM applied to the price */
export interface PricingAdjustmentFactor {
  /** Name of the factor (e.g. "urgency", "returning_customer") */
  factor: string;
  /** Whether this pushes the price up or down */
  direction: 'up' | 'down';
  /** How much this factor moves the price */
  magnitude: 'small' | 'medium' | 'large';
  /** Human-readable explanation */
  reasoning: string;
}

/** Output from the LLM pricing layer */
export interface LLMPricingResult {
  /** LLM's suggested price in pence */
  suggestedPricePence: number;
  /** LLM's time estimate in minutes (may differ from input) */
  timeEstimateMinutes: number;
  /** Internal reasoning chain (for ops review, not shown to customer) */
  reasoning: string;
  /** How confident the LLM is in this price */
  confidence: 'high' | 'medium' | 'low';
  /** Customer-facing headline, e.g. "Sorted Tonight" for emergency */
  contextualHeadline: string;
  /** Customer-facing value message */
  contextualMessage: string;
  /** Individual adjustment factors the LLM considered */
  adjustmentFactors: PricingAdjustmentFactor[];
}

// ---------------------------------------------------------------------------
// Layer 4: Guardrails
// ---------------------------------------------------------------------------

/** Output from the guardrail checks */
export interface GuardrailResult {
  /** Whether the price was below the floor and got bumped up */
  floorTriggered: boolean;
  /** Whether the price was above the ceiling and got capped */
  ceilingTriggered: boolean;
  /** Whether the implied margin passes our minimum threshold */
  marginCheckPassed: boolean;
  /** Human-readable list of adjustments made (empty if none) */
  adjustments: string[];
  /** Price before guardrails were applied, in pence */
  originalPricePence: number;
  /** Price after guardrails were applied, in pence */
  adjustedPricePence: number;
}

// ---------------------------------------------------------------------------
// Full Engine Output
// ---------------------------------------------------------------------------

/** Complete result from the contextual pricing engine */
export interface ContextualPricingResult {
  /** The final price to quote, in pence */
  finalPricePence: number;
  /** Price at each layer for transparency / debugging */
  layerBreakdown: {
    /** Layer 1: market reference rate */
    layer1ReferencePence: number;
    /** Layer 3: LLM-suggested price */
    layer3LLMSuggestedPence: number;
    /** Layer 4: final price after guardrails */
    layer4FinalPence: number;
  };
  /** Combined reasoning from all layers */
  reasoning: string;
  /** Overall confidence level */
  confidence: 'high' | 'medium' | 'low';
  /** Customer-facing headline */
  contextualHeadline: string;
  /** Customer-facing value message */
  contextualMessage: string;
  /** All adjustment factors from Layer 3 */
  adjustmentFactors: PricingAdjustmentFactor[];
  /** Guardrail check results from Layer 4 */
  guardrails: GuardrailResult;
}

// ---------------------------------------------------------------------------
// Multi-Line Pricing — Job Lines & Contextual Signals
// ---------------------------------------------------------------------------

/** A single job line in a multi-line quote */
export interface JobLine {
  /** Client-generated unique ID for this line */
  id: string;
  /** Free-text description of the work requested */
  description: string;
  /** Detected job category */
  category: JobCategory;
  /** Estimated time to complete this line item in minutes */
  timeEstimateMinutes: number;
  /** Optional material cost for this line in pence (trade/cost price, before margin) */
  materialsCostPence?: number;
}

/**
 * Raw contextual signals that the pricing engine uses alongside job lines.
 * Slimmed down to the 6 signals that actually move the price needle.
 */
export interface ContextualSignals {
  /** How urgently the customer needs the work done */
  urgency: 'standard' | 'priority' | 'emergency';
  /** Who is supplying materials */
  materialsSupply: 'customer_supplied' | 'we_supply' | 'labor_only';
  /** When the work will be carried out */
  timeOfService: 'standard' | 'after_hours' | 'weekend';
  /** Whether the customer has booked with us before */
  isReturningCustomer: boolean;
  /** Number of previous completed jobs (only if returning) */
  previousJobCount: number;
  /** Average price of previous jobs in pence (only if returning) */
  previousAvgPricePence: number;
}

// ---------------------------------------------------------------------------
// AI Job Description Parsing
// ---------------------------------------------------------------------------

/** Result from AI job description parsing */
export interface ParsedJobResult {
  /** Parsed job lines */
  lines: JobLine[];
  /** Contextual signals detected from the text */
  detectedSignals: {
    urgency: 'standard' | 'priority' | 'emergency' | null;
    materialsSupply: 'customer_supplied' | 'we_supply' | 'labor_only' | null;
    timeOfService: 'standard' | 'after_hours' | 'weekend' | null;
  };
}

// ---------------------------------------------------------------------------
// Multi-Line Pricing — Request & Result
// ---------------------------------------------------------------------------

/** Input for the multi-line contextual pricing engine */
export interface MultiLineRequest {
  /** One or more job lines to price together */
  lines: JobLine[];
  /** Raw contextual signals for this quote */
  signals: ContextualSignals;
  /** Free-text context about the customer captured by the VA after speaking with them */
  vaContext?: string;
  /**
   * Historical win rate percentage for similar quotes over the last 90 days
   * (e.g. 35 means 35% of similar quotes converted). Passed to the LLM so it
   * can calibrate confidence. Omitted when fewer than 5 comparable quotes exist.
   */
  historicalWinRate?: number;
}

/** Price result for a single line item */
export interface LineItemResult {
  /** ID matching the input JobLine */
  lineId: string;
  /** Description of the work */
  description: string;
  /** Job category used for pricing */
  category: JobCategory;
  /** Estimated time in minutes */
  timeEstimateMinutes: number;
  /** Layer 1 reference price for this line in pence */
  referencePricePence: number;
  /** Layer 3 LLM-suggested price for this line in pence */
  llmSuggestedPricePence: number;
  /** Final guarded price for this line in pence (labour only) */
  guardedPricePence: number;
  /** Individual adjustment factors applied to this line */
  adjustmentFactors: PricingAdjustmentFactor[];
  /** Material cost in pence (trade/cost price, before margin). 0 if no materials. */
  materialsCostPence: number;
  /** Material cost with margin applied (what the customer pays for materials) */
  materialsWithMarginPence: number;
  /**
   * Optional 1-2 sentence detailed description shown to the customer under the line title.
   * When present, the quote and invoice pages render this as muted sub-text.
   * Populated via the admin description-toggle flow (or manually for bespoke high-ticket jobs).
   */
  details?: string | null;
}

/** Batch discount applied when multiple lines are quoted together */
export interface BatchDiscount {
  /** Whether a batch discount was applied */
  applied: boolean;
  /** Discount percentage (0 if not applied) */
  discountPercent: number;
  /** Total savings from the discount in pence */
  savingsPence: number;
  /** Human-readable explanation of the discount logic */
  reasoning: string;
}

/** Full output from the multi-line contextual pricing engine */
export interface MultiLineResult {
  /** Price breakdown for each line item */
  lineItems: LineItemResult[];
  /** Sum of all line item guarded prices before batch discount, in pence (labour only) */
  subtotalPence: number;
  /** Total materials cost with margin across all lines, in pence */
  totalMaterialsWithMarginPence: number;
  /** Batch discount details (applied to labour only, not materials) */
  batchDiscount: BatchDiscount;
  /** Final price after batch discount + materials, in pence */
  finalPricePence: number;
  /** Price at each layer for transparency / debugging */
  layerBreakdown: {
    /** Layer 1: sum of all reference prices */
    layer1ReferencePence: number;
    /** Layer 3: sum of all LLM-suggested prices */
    layer3LLMSuggestedPence: number;
    /** Layer 4: final price after guardrails and batch discount */
    layer4FinalPence: number;
  };
  /** Combined reasoning from all layers */
  reasoning: string;
  /** Overall confidence level */
  confidence: 'high' | 'medium' | 'low';
  /** Customer-facing headline */
  contextualHeadline: string;
  /** Customer-facing value message */
  contextualMessage: string;
  /** 3-7 word polished job summary for the hero */
  jobTopLine?: string;
  /** Guardrail check results from Layer 4 */
  guardrails: GuardrailResult;
  /** LLM-generated customer-facing messaging */
  messaging: QuoteMessaging;
}

// ---------------------------------------------------------------------------
// Margin Preview (admin-only, returned alongside pricing results)
// ---------------------------------------------------------------------------

/** Per-line margin breakdown for a single line item */
export interface MarginPreviewLine {
  categorySlug: string;
  customerPricePence: number;
  /** Effective hourly rate the contractor earns (derived from revenue share or legacy WTBP) */
  wtbpHourlyPence: number;
  hours: number;
  contractorCostPence: number;
  marginPence: number;
  marginPercent: number;
  /** Revenue share tier: specialist | skilled | general | outdoor */
  tier?: string;
  /** Revenue share % for this tier (e.g. 45, 50, 55) */
  revenueSharePercent?: number;
  /** Which method set the pay: 'share' or 'floor' */
  payMethod?: string;
  /** Min hourly floor in pence */
  minHourlyPence?: number;
}

/** Full margin preview for a multi-line quote */
export interface MarginPreview {
  totalCostPence: number;
  totalMarginPence: number;
  totalMarginPercent: number;
  perLineMargin: MarginPreviewLine[];
  uncoveredCategories: string[];
  flags: string[];
}

// ---------------------------------------------------------------------------
// Multi-Line LLM Response (with messaging fields)
// ---------------------------------------------------------------------------

/** Extended LLM response structure that includes messaging alongside pricing */
export interface MultiLineLLMResponseWithMessaging {
  lines: Array<{
    lineId: string;
    pricePence: number;
    confidence: number;
    reasoning: string;
  }>;
  batchDiscountPercent: number;
  batchDiscountReason: string;
  overallConfidence: number;
  reasoning: string;
  // Messaging fields
  contextualHeadline: string;
  contextualMessage: string;
  proposalSummary: string;
  valueBullets: string[];
  whatsappValueLines: string[];
  whatsappClosing: string;
  recommendedLayout: LayoutTier;
}

// ---------------------------------------------------------------------------
// Multi-Line Test Scenarios
// ---------------------------------------------------------------------------

/** Pre-built test scenario for the multi-line pricing engine */
export interface MultiLineTestScenario {
  /** Short name shown in the scenario picker */
  name: string;
  /** What this scenario is testing */
  description: string;
  /** Full multi-line request for the scenario */
  request: MultiLineRequest;
}

// ---------------------------------------------------------------------------
// Comparison: Old EVE vs New Contextual
// ---------------------------------------------------------------------------

/** Side-by-side comparison of EVE and contextual pricing for the same job */
export interface PricingComparisonResult {
  /** Old EVE engine output */
  eve: {
    pricePence: number;
    segment: string;
    valueMultiplier: number;
    hourlyRatePence: number;
  };
  /** New contextual engine output */
  contextual: ContextualPricingResult;
  /** Difference between the two engines */
  delta: {
    /** Absolute difference in pence (contextual minus EVE) */
    pence: number;
    /** Percentage difference */
    percent: number;
    /** Whether contextual is higher, lower, or the same */
    direction: 'higher' | 'lower' | 'same';
  };
  /** The input context used for both engines */
  inputContext: PricingContext;
  /** ISO 8601 timestamp of when the comparison was run */
  timestamp: string;
}

// ---------------------------------------------------------------------------
// Test Scenarios
// ---------------------------------------------------------------------------

/** Pre-built test scenario for the comparison UI */
export interface TestScenario {
  /** Short name shown in the scenario picker */
  name: string;
  /** What this scenario is testing */
  description: string;
  /** Full pricing context for the scenario */
  context: PricingContext;
}
