/**
 * SEO service content — rich, page-ready, service-specific copy for every slug
 * in SEO_SERVICES. This is the substance the T2/T3 renderers turn into visible
 * page body + FAQPage JSON-LD, and it must clear the thin-content guard
 * (>= 250 visible words, >= 3 FAQ items).
 *
 * Templates carry literal {service}, {place} and {city} tokens; the renderer
 * substitutes them ({place} = a suburb name on T3, or the city name on T2).
 * UK spelling throughout. Copy is distinct per trade — no boilerplate reuse.
 * Trust facts (£2M insured, 4.9 stars / 127 reviews) mirror SEO_BRAND.
 */
import type { SeoServiceContent } from '../contract';

const SERVICES: SeoServiceContent[] = [
    {
        slug: 'handyman',
        label: 'Handyman',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — 4.9★, £2M Insured',
        metaDescriptionTemplate: 'Trusted {service} in {place}. Flat-pack, shelves, TV mounting, repairs and odd jobs done right first time. 4.9★ from 127 reviews, £2M insured. Get a quote.',
        intro: 'A reliable local handyman for the jobs that pile up — the wobbly shelf, the door that won\'t close, the flat-pack still in its box. We turn up when we say we will, work tidily, and get through your whole list in one visit rather than dragging it out. Every job is backed by our workmanship guarantee.',
        benefits: [
            'One vetted tradesperson for your entire snag list — no juggling multiple contractors',
            'Fully equipped van, so most small jobs are done same visit with no return trips',
            'Transparent hourly or fixed-price quotes agreed before we start — no surprise add-ons',
            'Punctual arrival windows with a text when we\'re on the way',
            '£2M public liability insurance and a workmanship guarantee on everything we touch',
            'Rated 4.9 stars across 127 verified customer reviews',
        ],
        faq: [
            { q: 'How much does a handyman cost in {city}?', a: 'Most small jobs start from around £89 for the first hour including call-out, with fixed quotes for larger lists. We confirm the price in writing before any work begins, so you always know the cost up front.' },
            { q: 'Can you do several small jobs in one visit?', a: 'Yes — that\'s what we\'re best at. Send us your list when you book and we\'ll bring the right tools and materials to clear as much of it as possible in a single, cost-effective visit.' },
            { q: 'What jobs won\'t a handyman take on?', a: 'We handle general repairs, mounting, assembly and maintenance. Notifiable gas, full rewires and structural work go to our specialist trades instead, and we\'ll tell you honestly if a job needs one.' },
            { q: 'Are you insured and guaranteed?', a: 'Every handyman carries £2M public liability cover, and all workmanship is guaranteed. If something isn\'t right, we come back and put it right at no charge.' },
        ],
        priceFrom: '£89',
    },
    {
        slug: 'painter-decorator',
        label: 'Painting & Decorating',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Clean, Tidy, 4.9★',
        metaDescriptionTemplate: 'Professional painters and decorators in {place}. Interior and exterior painting, wallpapering and full room refreshes with dust-sheeted, tidy prep. £2M insured, 4.9★.',
        intro: 'Sharp lines, even coverage and proper preparation are what separate a decorator from a bloke with a brush. We fill, sand and mask before a drop of paint goes on, protect your floors and furniture, and leave the room cleaner than we found it. From a single feature wall to a whole house repaint.',
        benefits: [
            'Thorough prep — filling, caulking, sanding and priming — so the finish lasts, not just looks good on day one',
            'Trade-quality Dulux and Farrow & Ball paints applied to a cutting-in standard',
            'Dust sheets, masking and daily tidy-up to keep your home liveable while we work',
            'Interior and exterior work, including wallpaper hanging and stripping',
            'Fixed room-by-room quotes so you can stage the work to your budget',
            '£2M insured with a guarantee against peeling, flaking or missed coverage',
        ],
        faq: [
            { q: 'How much does it cost to paint a room in {city}?', a: 'A standard box bedroom typically starts from around £250 including materials, depending on ceiling height, condition and the number of coats. We give a fixed quote after seeing the room or photos.' },
            { q: 'Do you supply the paint or do I?', a: 'Either works. Most customers let us supply trade paint at cost, but if you\'ve chosen a specific colour or brand we\'re happy to work with what you provide.' },
            { q: 'How long will my rooms be out of use?', a: 'A single room is usually a one to two day job including prep and two coats. We\'ll give you a clear schedule so you can plan around it.' },
            { q: 'Can you fix cracks and damp patches before painting?', a: 'Yes. We fill cracks, make good damaged plaster and treat stains with the right primer so they don\'t bleed back through your new paint.' },
        ],
        priceFrom: '£250',
    },
    {
        slug: 'gutter-cleaning',
        label: 'Gutter Cleaning',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Vacuum + Photo Proof',
        metaDescriptionTemplate: 'Gutter cleaning in {place} from the ground with a high-reach vacuum. Before-and-after photos, downpipes cleared, no ladders on your roof. £2M insured, 4.9★.',
        intro: 'Blocked gutters cause damp, stained walls and overflowing during every downpour. We clear yours with a high-reach vacuum system from the safety of the ground — no ladders leaning on your gutters, no walking your roof. You get before-and-after photos so you can see the job was actually done.',
        benefits: [
            'Ground-based high-reach vacuum clears moss, silt and leaves without risky ladder work',
            'Before-and-after camera footage and photos sent to you as proof',
            'Downpipes and outlets checked and flushed, not just the visible channels',
            'Reaches three-storey and conservatory gutters most window cleaners can\'t',
            'No mess left behind — debris is bagged and taken away',
            '£2M insured with a re-clean guarantee if a run blocks again within 30 days',
        ],
        faq: [
            { q: 'How much is gutter cleaning in {city}?', a: 'A typical semi-detached starts from around £69, with terraces a little less and larger detached or three-storey homes priced on frontage. We quote a fixed price from your address before we attend.' },
            { q: 'How do you clean gutters without ladders?', a: 'We use a carbon-fibre vacuum pole system operated from the ground, with a camera on the end so we can see and photograph inside each gutter run as we clear it.' },
            { q: 'Do you clear the downpipes too?', a: 'Yes — a clear gutter that drains into a blocked downpipe still overflows, so we check and flush the outlets and downpipes as part of the standard job.' },
            { q: 'How often should gutters be cleaned?', a: 'Once a year suits most homes, or twice if you have overhanging trees. We can set a reminder so you don\'t have to think about it.' },
        ],
        priceFrom: '£69',
    },
    {
        slug: 'fencing',
        label: 'Fencing',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Posts Set in Concrete',
        metaDescriptionTemplate: 'Fence installation and repair in {place}. Feather-edge, panel and post-and-rail fencing with concrete-set posts. Old fence removed, waste taken away. £2M insured, 4.9★.',
        intro: 'A fence is only as good as its posts. We set ours in concrete to the correct depth so your fence stays upright through the first winter gale, not just the first summer. From replacing a few storm-damaged panels to a full boundary in feather-edge or closeboard, we take away the old timber and leave the line clean and level.',
        benefits: [
            'Posts dug and set in postcrete at proper depth for genuine wind resistance',
            'Concrete gravel boards available so panels never sit in wet ground and rot',
            'Feather-edge, closeboard, panel and post-and-rail options to suit look and budget',
            'Old fence, posts and concrete broken out and removed — no waste left for you',
            'Levels and boundary line checked so runs are straight and gates swing true',
            '£2M insured with a guarantee on posts and workmanship',
        ],
        faq: [
            { q: 'How much does a new fence cost in {city}?', a: 'Panel fencing is commonly around £90 to £120 per metre installed including posts, gravel boards and waste removal, depending on height and ground. We quote per your boundary after a look or photos.' },
            { q: 'Do you concrete the posts in?', a: 'Yes, always. We set posts in postcrete to the correct depth — this is the single biggest factor in whether a fence survives a windy winter, so we never skip it.' },
            { q: 'Will you remove my old fence?', a: 'We break out the old panels, posts and concrete footings and take the lot away, so you\'re left with a clean boundary ready for the new fence.' },
            { q: 'How long does fencing take to install?', a: 'A typical garden run of 15 to 20 metres is usually one to two days, allowing the postcrete to set before panels take full wind load.' },
        ],
        priceFrom: '£90/m',
    },
    {
        slug: 'plasterer',
        label: 'Plastering',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Skim-Ready Walls, 4.9★',
        metaDescriptionTemplate: 'Plastering in {place}. Re-skims, patch repairs, ceilings and full renders finished flat and ready to paint. Tidy dust control, £2M insured, 4.9★ from 127 reviews.',
        intro: 'A good skim disappears — you only notice bad plastering. We prep, PVA and float to a genuinely flat, paint-ready finish with no visible trowel lines, blown patches or sunken corners. Whether it\'s a single water-damaged ceiling, a tired room in need of a re-skim, or bare brick that needs dot-and-dabbing, we leave it smooth and clean.',
        benefits: [
            'Flat, polished, paint-ready finish with no trowel marks or fat edges',
            'Re-skims over sound old plaster, plus patch repairs blended seamlessly into existing walls',
            'Ceilings, coving, dot-and-dab plasterboarding and full renders undertaken',
            'Proper dust sheeting and edge protection to contain mess to the work area',
            'Realistic drying advice so you don\'t paint too soon and trap moisture',
            '£2M insured with a guarantee against cracking and blown patches',
        ],
        faq: [
            { q: 'How much does plastering cost in {city}?', a: 'Re-skimming an average room ceiling or wall commonly starts from around £180 to £250, with whole rooms priced by size and condition. We quote fixed after seeing the surfaces.' },
            { q: 'How long before I can paint new plaster?', a: 'Fresh plaster needs to dry fully — usually four to seven days depending on ventilation and season — before a watered-down mist coat and then your topcoats. We\'ll advise for your specific job.' },
            { q: 'Can you patch a damaged area rather than redo the whole wall?', a: 'Yes. We can cut out and make good a damaged section and feather it into the surrounding plaster, though a full re-skim gives the most seamless result on very patchy walls.' },
            { q: 'Do you plaster over artex or bare brick?', a: 'Both. We can skim over sound artex or plasterboard, and dot-and-dab or bond-and-scratch coat bare brick before skimming to a flat finish.' },
        ],
        priceFrom: '£180',
    },
    {
        slug: 'kitchen-fitting',
        label: 'Kitchen Fitting',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Full Fit, One Team',
        metaDescriptionTemplate: 'Kitchen fitting in {place}. Units, worktops, appliances and finishing by one coordinated team. Flat-pack or rigid, any supplier. £2M insured, 4.9★ from 127 reviews.',
        intro: 'A kitchen fit is really several trades in the right order — strip out, first fix, units, worktops, appliances and finishing. We coordinate the lot so cabinets sit level, doors line up, and worktops meet the wall without gaps. Whether it\'s a Howdens, Wren, Wickes or IKEA kitchen, we fit it properly and hand it back ready to cook in.',
        benefits: [
            'One project-managed team so plumbing, electrics and joinery happen in the right sequence',
            'Rigid or flat-pack units from any supplier assembled and hung dead level',
            'Laminate, solid wood and stone-effect worktops cut, jointed and sealed cleanly',
            'Appliances plumbed, wired and tested; old kitchen stripped out and removed',
            'Tiling, splashbacks and end panels finished so there are no raw edges',
            '£2M insured with a workmanship guarantee across the whole install',
        ],
        faq: [
            { q: 'How much does it cost to fit a kitchen in {city}?', a: 'Fitting labour for an average kitchen typically ranges from around £1,800 to £3,500 depending on unit count, worktop type and whether walls or floors need work. We quote fixed after a survey.' },
            { q: 'How long does a kitchen installation take?', a: 'A standard kitchen is usually five to ten working days from strip-out to finish, depending on size and how much plastering, tiling or electrical work is involved.' },
            { q: 'Do you supply the kitchen or just fit it?', a: 'We\'re happy to fit a kitchen you\'ve bought from any supplier, or advise on suppliers if you\'d prefer. Fitting-only is our most popular option and keeps costs clear.' },
            { q: 'Can you handle the plumbing and electrics too?', a: 'Yes — our team covers first-fix plumbing and electrical connections as part of the fit, with certified sign-off where regulations require it.' },
        ],
        priceFrom: '£1,800',
    },
    {
        slug: 'carpenter',
        label: 'Carpentry',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Bespoke Joinery, 4.9★',
        metaDescriptionTemplate: 'Carpentry and joinery in {place}. Doors, skirting, fitted wardrobes, shelving and bespoke storage cut and fitted on site. £2M insured, 4.9★ from 127 reviews.',
        intro: 'From hanging a door that finally closes on the latch to building fitted alcove storage that looks like it was always there, good carpentry is about clean joints and patient fitting. We cut and scribe on site so units follow your walls and floors — which are never quite square — and finish flush, level and ready for paint.',
        benefits: [
            'Doors hung and eased to close cleanly, with locks, hinges and handles fitted',
            'Bespoke alcove units, shelving and fitted wardrobes built to your space',
            'Skirting, architrave, dado and picture rails supplied, mitred and fitted',
            'Stud walls, loft hatches, boxing-in and second-fix joinery undertaken',
            'On-site scribing so units follow real walls and floors, not perfect ones',
            '£2M insured with a workmanship guarantee on every joint we cut',
        ],
        faq: [
            { q: 'How much does a carpenter cost in {city}?', a: 'Day rates commonly run from around £220 to £280 depending on the work, with fixed prices for defined jobs like hanging a door or fitting shelves. We confirm before starting.' },
            { q: 'Can you build fitted wardrobes or alcove units?', a: 'Yes — bespoke fitted storage is one of our most requested jobs. We build to your alcove or wall, scribing to the space so there are no gaps, and can leave it primed or fully finished.' },
            { q: 'Do you supply the timber and materials?', a: 'We can supply everything and itemise it in the quote, or work with materials you\'ve already bought. Either way the price is agreed in writing up front.' },
            { q: 'Will you fit doors I\'ve bought myself?', a: 'Absolutely. We\'ll hang and adjust doors you\'ve purchased, fit the ironmongery and make sure they close properly on the latch.' },
        ],
        priceFrom: '£220',
    },
    {
        slug: 'tiler',
        label: 'Tiling',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Level, Sealed, 4.9★',
        metaDescriptionTemplate: 'Wall and floor tiling in {place}. Bathrooms, kitchens and splashbacks laid flat with even grout lines and proper sealing. £2M insured, 4.9★ from 127 reviews.',
        intro: 'Tiling lives or dies on the setting-out. We plan the layout so cut tiles fall in the least visible places, walls are level, and you don\'t end up with a sliver of tile in the corner. Substrates are prepped and primed, grout lines are even, and wet areas are properly tanked and sealed so water stays where it should.',
        benefits: [
            'Careful setting-out so full tiles sit where they show and cuts hide in corners',
            'Substrates checked, levelled and primed so tiles bond and don\'t debond later',
            'Wet areas tanked and sealed before tiling for real waterproofing, not just grout',
            'Ceramic, porcelain, natural stone and mosaic, walls and floors',
            'Even grout lines finished cleanly, with silicone to movement joints not grout',
            '£2M insured with a guarantee against loose tiles and cracked grout',
        ],
        faq: [
            { q: 'How much does tiling cost per square metre in {city}?', a: 'Wall tiling commonly runs from around £40 to £60 per square metre for labour, with floors and natural stone a little more. We quote by area and tile type after seeing the space.' },
            { q: 'Do you waterproof before tiling a shower?', a: 'Yes. Shower and wet areas are tanked with a waterproof membrane before tiling — grout and adhesive alone are not waterproof, so this step is what actually keeps water out.' },
            { q: 'Can you tile over existing tiles?', a: 'Sometimes, if the existing tiles are sound and flat, but it raises the surface and rarely gives the best result. We\'ll advise honestly whether to overtile or strip back first.' },
            { q: 'How long does a bathroom retile take?', a: 'A typical bathroom is around three to five days depending on size, tile format and whether the walls need preparation or boarding first.' },
        ],
        priceFrom: '£40/m²',
    },
    {
        slug: 'bathroom-fitting',
        label: 'Bathroom Fitting',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Full Refit, One Team',
        metaDescriptionTemplate: 'Bathroom fitting in {place}. Full refits, suites, showers and wet rooms plumbed, tiled and finished by one team. £2M insured, 4.9★ from 127 reviews.',
        intro: 'A bathroom refit touches plumbing, tiling, electrics and joinery, and the order matters. We manage the whole job — strip-out, first-fix pipework, waterproofing, suite, tiling and finishing — so it comes together watertight and level. You deal with one team from empty room to first shower, not five contractors blaming each other.',
        benefits: [
            'Complete project management — one team for plumbing, tiling, electrics and finishing',
            'Wet areas fully tanked and waterproofed before any tile goes on',
            'Baths, showers, wet rooms, basins and WCs supplied or fitted to your spec',
            'Old suite stripped out and removed, floors levelled and made ready',
            'Extractor fans and IP-rated lighting fitted with certified electrical sign-off',
            '£2M insured with a workmanship guarantee across the whole refit',
        ],
        faq: [
            { q: 'How much does a new bathroom cost in {city}?', a: 'A full refit including labour typically ranges from around £3,500 to £7,000 depending on suite quality, tiling area and whether you\'re changing the layout. We quote fixed after a survey.' },
            { q: 'How long does a bathroom refit take?', a: 'Most bathrooms are seven to twelve working days from strip-out to finish, allowing time for tanking, tiling and grout to cure properly before use.' },
            { q: 'Can you move the toilet or basin to a new position?', a: 'Yes — reconfiguring the layout is common. We\'ll advise on what\'s practical given soil pipe runs and floor structure, and price the pipework changes clearly.' },
            { q: 'Do you supply the suite or do I?', a: 'Either. Many customers choose their own suite and tiles and we fit them; others let us supply and itemise everything. The quote is agreed in writing before we start.' },
        ],
        priceFrom: '£3,500',
    },
    {
        slug: 'landscaping',
        label: 'Garden & Landscaping',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Patios, Turf, Beds, 4.9★',
        metaDescriptionTemplate: 'Garden and landscaping in {place}. Patios, turfing, planting, sleeper beds and full garden makeovers with proper drainage and foundations. £2M insured, 4.9★.',
        intro: 'A garden that lasts starts below the surface — with proper sub-bases, falls for drainage and edges that hold. We lay patios and paths on the right foundation so they don\'t sink or pool, turf onto prepared soil so it takes, and build raised beds and boundaries that stay square. From a tidy-up to a full redesign.',
        benefits: [
            'Patios and paths laid on compacted sub-base with correct falls so water drains away',
            'Turfing onto properly prepared, levelled and rotavated soil for strong rooting',
            'Sleeper and brick raised beds, borders and retaining edges built square and solid',
            'Fencing, decking, planting and clearance can be combined into one garden project',
            'Green waste, old slabs and spoil removed — no skip clutter left behind',
            '£2M insured with a workmanship guarantee on hard landscaping',
        ],
        faq: [
            { q: 'How much does landscaping cost in {city}?', a: 'It varies hugely by scope — a new patio commonly starts from around £120 per square metre laid, while full makeovers are priced by design. We quote after seeing the garden.' },
            { q: 'Will a new patio drain properly?', a: 'Yes — we build in the correct fall away from your house and lay on a compacted sub-base so surface water runs off rather than pooling or seeping toward the walls.' },
            { q: 'Can you take away all the old materials and waste?', a: 'We remove old slabs, spoil, turf and green waste as part of the job, so you\'re not left arranging a skip or disposal yourself.' },
            { q: 'What time of year is best for turfing?', a: 'Turf can be laid most of the year except hard frost or drought, but spring and autumn are ideal. We\'ll advise on aftercare watering whenever we lay it.' },
        ],
        priceFrom: '£120/m²',
    },
    {
        slug: 'pressure-washing',
        label: 'Pressure Washing',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Driveways & Patios, 4.9★',
        metaDescriptionTemplate: 'Pressure washing in {place}. Driveways, patios, decking and paths cleaned back to life, then re-sanded and sealed. £2M insured, 4.9★ from 127 reviews.',
        intro: 'Years of green algae, black spot and moss come off in a single visit with the right kit and technique. We use rotary surface cleaners for an even finish without the zebra-striping a lance leaves behind, then re-sand block paving and can seal it so it stays cleaner for longer. Driveways, patios, paths, decking and render.',
        benefits: [
            'Rotary surface cleaners give an even, stripe-free finish across the whole area',
            'Block paving re-sanded with kiln-dried sand so it locks tight and resists weeds',
            'Optional sealing to slow regrowth of algae and keep colour looking fresh',
            'Safe pressure settings for delicate surfaces like render, decking and natural stone',
            'Drains and gullies rinsed clear of the silt washed off, not left blocked',
            '£2M insured with a satisfaction guarantee on the finished clean',
        ],
        faq: [
            { q: 'How much does pressure washing a driveway cost in {city}?', a: 'A typical driveway starts from around £120 depending on size and how heavily soiled it is, with re-sanding and sealing quoted as optional extras. We price from your address.' },
            { q: 'Will pressure washing damage my block paving?', a: 'Not when done correctly. We wash out and then replace the kiln-dried jointing sand, so the blocks stay locked in place rather than loose after cleaning.' },
            { q: 'Should I seal the driveway after cleaning?', a: 'Sealing is optional but worthwhile — it slows algae and weed regrowth, stabilises the sand and keeps the colour vivid. We can apply it once the surface has fully dried.' },
            { q: 'How long does the driveway take to dry?', a: 'The surface is walkable almost straight away; if we\'re sealing, we let it dry for 24 hours first so the sealer bonds properly.' },
        ],
        priceFrom: '£120',
    },
    {
        slug: 'decking',
        label: 'Decking',
        deliverability: 'core',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Timber & Composite, 4.9★',
        metaDescriptionTemplate: 'Decking installation in {place}. Timber and composite decks built on solid, ventilated frames with hidden fixings. Old deck removed. £2M insured, 4.9★.',
        intro: 'A deck that flexes or rots underfoot was built on a poor frame. We build ours on properly spaced, ventilated joists set on solid footings, with a slight fall so water runs off and boards stay dry. Whether you want low-maintenance composite or classic softwood, it comes out flat, secure and ready to furnish.',
        benefits: [
            'Ventilated sub-frame on solid footings so the deck stays firm and the timber breathes',
            'Composite and treated softwood options to balance looks against maintenance',
            'Hidden or countersunk fixings for a clean top surface with no proud screw heads',
            'Slight fall built in so rainwater sheds and boards don\'t sit wet and cup',
            'Old decking, frame and footings removed and cleared as part of the job',
            '£2M insured with a workmanship guarantee on the frame and boards',
        ],
        faq: [
            { q: 'How much does decking cost in {city}?', a: 'Softwood decking commonly starts from around £120 per square metre installed and composite from around £180, including the sub-frame. We quote per your area and board choice.' },
            { q: 'Is composite decking worth the extra cost?', a: 'If you want to avoid annual sanding, oiling and the risk of splinters, composite pays back in low maintenance and longevity. Softwood costs less up front but needs regular upkeep.' },
            { q: 'Will the deck get slippery in winter?', a: 'We can fit grooved or anti-slip boards and build in drainage falls so water sheds quickly, which greatly reduces the algae that makes decking slippery.' },
            { q: 'How long does it take to build a deck?', a: 'A typical garden deck is two to four days depending on size, height and whether groundworks or steps and balustrade are involved.' },
        ],
        priceFrom: '£120/m²',
    },
    {
        slug: 'roofer',
        label: 'Roofing',
        deliverability: 'sub',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Vetted Roofers, £2M Insured',
        metaDescriptionTemplate: 'Roofing in {place}. Slipped tiles, leaks, ridge repointing, flat roofs and full re-roofs by vetted, insured roofers. Free inspection and photo report. 4.9★.',
        intro: 'Roof problems only get more expensive the longer they leak, but they also attract more dodgy traders than any other trade. Every roofer we send is vetted, insured and works to a written quote after a proper inspection — with photos of the actual fault, not a scare story. From a single slipped tile to a full re-roof.',
        benefits: [
            'Vetted, insured roofers only — no doorstep traders or pressure selling',
            'Inspection with photos of the real fault so you can see what\'s being fixed and why',
            'Slipped and cracked tiles, ridge and verge repointing, and flashing repairs',
            'Flat roof recovers in EPDM rubber and GRP fibreglass, plus full pitched re-roofs',
            'Written, itemised quotes — repair options first, replacement only when genuinely needed',
            '£2M insured work with a workmanship guarantee on repairs and re-roofs',
        ],
        faq: [
            { q: 'How much does roof repair cost in {city}?', a: 'A small repair like refixing slipped tiles often starts from around £150 to £250, while larger works are quoted after inspection. We always show you the fault before pricing.' },
            { q: 'Can you find where my roof is leaking?', a: 'Yes — we trace leaks back from where they show inside to the actual entry point, which is often some distance away, and photograph it so you understand the repair.' },
            { q: 'Do I need a full new roof or just a repair?', a: 'Usually a repair. We only recommend a re-roof when the covering is genuinely at the end of its life, and we\'ll give you honest repair-versus-replace options in writing.' },
            { q: 'Are your roofers insured?', a: 'Every roofer we send is vetted and works under £2M insurance, with a workmanship guarantee — important for a trade where uninsured cowboys are unfortunately common.' },
        ],
        priceFrom: '£150',
    },
    {
        slug: 'locksmith',
        label: 'Locksmith',
        deliverability: 'sub',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Non-Destructive Entry, 4.9★',
        metaDescriptionTemplate: 'Locksmith in {place}. Lockouts, lock changes, uPVC repairs and insurance-grade upgrades by vetted, DBS-checked locksmiths. Non-destructive entry. £2M insured.',
        intro: 'Locked out, or worried after a break-in or a lost key? Our vetted locksmiths get you back in without smashing the lock wherever possible, then advise on secure, insurance-approved replacements. Every locksmith is DBS-checked and insured, with clear pricing agreed before work — no inflated on-the-doorstep bills.',
        benefits: [
            'Non-destructive entry techniques used first, so you don\'t always pay for a new lock',
            'DBS-checked, vetted locksmiths — the security of who\'s at your door matters',
            'uPVC door and multipoint mechanism repairs, not just full lock replacement',
            'Insurance-approved British Standard and anti-snap euro cylinder upgrades',
            'Clear price agreed before work starts — no doorstep price hikes',
            '£2M insured with a guarantee on parts and fitting',
        ],
        faq: [
            { q: 'How much does a locksmith cost in {city}?', a: 'A standard lockout or lock change commonly starts from around £75 to £120 depending on the lock and time of day. We give a clear price on the phone before attending where possible.' },
            { q: 'Will you have to drill or break my lock?', a: 'We use non-destructive entry methods first, which open most locks without damage. Drilling is a last resort for high-security or already-faulty locks, and we tell you before doing it.' },
            { q: 'Can you fit locks that meet my insurance requirements?', a: 'Yes — we fit British Standard BS3621 locks and anti-snap cylinders that satisfy most home insurance policies, and can advise on what your policy needs.' },
            { q: 'My uPVC door won\'t lock — can you fix it?', a: 'Usually yes. uPVC doors often fail at the multipoint mechanism rather than the barrel, and we can repair or replace the mechanism rather than the whole door.' },
        ],
        priceFrom: '£75',
    },
    {
        slug: 'plumber',
        label: 'Plumbing',
        deliverability: 'sub',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Vetted Plumbers, 4.9★',
        metaDescriptionTemplate: 'Plumbing in {place}. Leaks, taps, toilets, radiators and bathroom plumbing by vetted, insured plumbers. Clear pricing, no call-out surprises. £2M insured, 4.9★.',
        intro: 'A dripping tap wastes water; a hidden leak wrecks a ceiling. Our vetted plumbers fix the cause, not just the symptom, and price the job clearly before starting rather than watching the meter run. From a running toilet or a new tap to full bathroom pipework and radiator work — done tidily and tested before we leave.',
        benefits: [
            'Vetted, insured plumbers who diagnose the actual cause of leaks and low pressure',
            'Taps, mixers, toilets, ballvalves and waste traps repaired or replaced',
            'Radiators, valves and towel rails fitted and balanced; airlocks cleared',
            'Bathroom and kitchen first-fix and second-fix pipework undertaken',
            'Clear pricing agreed up front — no meter running while you wait',
            '£2M insured with a workmanship guarantee and a test before we leave',
        ],
        faq: [
            { q: 'How much does a plumber cost in {city}?', a: 'Small jobs like a tap or toilet repair commonly start from around £80 to £130 including call-out, with larger work quoted up front. We agree the price before starting.' },
            { q: 'Can you find a leak I can\'t see?', a: 'Yes — we trace concealed leaks back to the source, whether it\'s pipework, a seal or an overflow, and fix the cause rather than just mopping up the symptom.' },
            { q: 'Do you fit taps and toilets I\'ve bought myself?', a: 'Absolutely. We\'ll fit fixtures you\'ve purchased, check the seals and connections, and test everything for leaks before we leave.' },
            { q: 'Is your plumbing work guaranteed?', a: 'Yes — every plumber we send is insured and the workmanship is guaranteed. Note that notifiable gas work is handled separately by our Gas Safe registered engineers.' },
        ],
        priceFrom: '£80',
    },
    {
        slug: 'electrician',
        label: 'Electrical',
        deliverability: 'sub',
        h1Template: '{service} in {place}',
        metaTitleTemplate: '{service} in {place} | Handy Services — Certified Electricians, 4.9★',
        metaDescriptionTemplate: 'Electrical work in {place}. Sockets, lighting, consumer units, fault-finding and EICR certificates by registered, insured electricians. Certified sign-off. £2M insured.',
        intro: 'Electrics are the one trade where a bodge can genuinely be dangerous, which is why every electrician we send is registered and certifies their work. From extra sockets and downlighting to consumer unit upgrades, fault-finding and landlord safety certificates, the job is done to current wiring regulations and signed off with the paperwork to prove it.',
        benefits: [
            'Registered, insured electricians working to current BS 7671 wiring regulations',
            'Sockets, switches, lighting, downlights and outdoor power installed neatly',
            'Consumer unit (fuse board) upgrades with RCD protection for safety',
            'Fault-finding for tripping circuits, dead sockets and flickering lights',
            'EICR reports and landlord electrical safety certificates issued',
            '£2M insured with certified sign-off on all notifiable work',
        ],
        faq: [
            { q: 'How much does an electrician cost in {city}?', a: 'Small jobs like fitting a socket or light commonly start from around £90 to £140 including call-out, with larger work such as a consumer unit quoted after a look. Prices are agreed up front.' },
            { q: 'Do you provide a certificate for the work?', a: 'Yes — notifiable work is certified and, where required, registered with building control, so you get the paperwork you need for safety and for selling or letting the property.' },
            { q: 'Can you do an EICR for my rental property?', a: 'We carry out Electrical Installation Condition Reports and issue landlord safety certificates, which are a legal requirement for rented homes in England.' },
            { q: 'My electrics keep tripping — can you find the fault?', a: 'Yes. We methodically isolate circuits to trace the cause of nuisance tripping — often a faulty appliance, damaged cable or failing RCD — and put it right safely.' },
        ],
        priceFrom: '£90',
    },
];

/** Indexed for O(1) lookup by the content API. */
export const SEO_SERVICE_CONTENT: SeoServiceContent[] = SERVICES;
